### ISSUE TITLE
[Question]: ROS raspberry PI 4B setup doc & RAM issue

### ISSUE THREAD

**Issue by Astreptocoque** [Interbotix/interbotix_ros_manipulators#104]
### Question

_This post is a description of an issue I encountered, but having solved it, I post here as a question. I'd like to report my problem to help other users and the interbotix team._ 

I'm starting a project with the WidowX 250 and have been setting up my Raspberry Pi as the robot controller with ROS2.
Following the ROS2 interbotix documentation ([link](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros_interface/ros2/software_setup.html#raspberry-pi-4b-arm64-architecture)), the link for the "Raspberry Pi 4B Setup instructions" for ROS2 is broken : [https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros_interface/ros2/raspberry_pi_setup.html](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros_interface/ros2/raspberry_pi_setup.html) (under `Raspberry Pi 4B` sub-section).

Therefore, I followed the guide from the ROS1 doc ([link](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros_interface/ros1/raspberry_pi_setup.html)). This page says that a Pi with 4 Gb of RAM is enough. However, I ran into OOM errors while using the installation script `./xsarm_amd64_install.sh`.

To overcome the error, I had to force colcon sequential build and add swap memory to the PI (`if colcon build --executor sequential; then` on line 289 of the script). The build then finished correctly.

I am a novice and I don't know if my issue is related to something specific to my setup. I did not do anything special apart from following the guide.
My question/remark is to **report the broken link** and if the 4Gb Pi is still recommended for ROS2, the script could be updated to **ask the user if they want to use sequential build**, as well as a mention for swap memory. I am discovering the Raspberry Pi and using swap memory was easy but it is deactivated by default. 

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

### Additional Info

Raspberry Pi 4B 4Gb
Ubuntu server 22.04.03 LTS 
ubuntu-MATE-deksop at first try, with command line only after fresh reinstall to spare RAM

**Comment by LSinterbotix** [comment]
The missing ROS 2 RPi setup page has been [added](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros_interface/ros2/raspberry_pi_setup.html) in the latest docs update.
