### ISSUE TITLE
[Question]: Jetson AGX Xavier support

### ISSUE THREAD

**Issue by OrestisTzaf** [Interbotix/interbotix_ros_manipulators#108]
### Question

Hello, 
I wanted to ask if the packages of the ViperX 250 have been tested and working properly in the jetson xavier agx (ubuntu18.04 & ros melodic).
Thanks.

### Robot Model

ViperX 250

### Operating System

Ubuntu 18.04

### ROS Version

ROS 1 Melodic

**Comment by LSinterbotix** [comment]
The packages have not been tested on that platform and OS. However, I expect that you will have no issues installing the core interbotix_ros_xsarms packages, with the possible exclusion of interbotix_xsarm_perception.
