### ISSUE TITLE
[Question]: Not able to launch the physical arm

### ISSUE THREAD

**Issue by MurshidKc010** [Interbotix/interbotix_ros_manipulators#111]
### Question

I am not able to launch my physical arm in RViz by using the following ROS commands

roslaunch interbotix_xsarm_control xsarm_control.launch robot_model:=wx200

I am getting this error in the terminal

[wx200/xs_sdk-4] process has died [pid 66231, exit code -11, cmd /home/murshid/interbotix_ws/devel/lib/interbotix_xs_sdk/xs_sdk __name:=xs_sdk __log:=/home/murshid/.ros/log/17de29a8-4684-11ee-bb59-7f523c85ef49/wx200-xs_sdk-4.log].
log file: /home/murshid/.ros/log/17de29a8-4684-11ee-bb59-7f523c85ef49/wx200-xs_sdk-4*.log

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

### Additional Info

Attaching the screenshot of the error for your reference

![Screenshot from 2023-08-30 13-31-40](https://github.com/Interbotix/interbotix_ros_manipulators/assets/143523422/29d092a2-0188-484d-8a74-8cffe14a74a5)

**Comment by swiz23** [comment]
Can you check which robotic arm you purchased? The WX200 arm should only have Dynamixel IDs ranging from 1 to 7. From the output in the terminal, there seems to be an ID 8...

**Comment by swiz23** [comment]
I also am a bit confused as to why the shoulder shadow motor is showing up as a model XH430. Shouldn't that be an XM430 servo?

**Comment by MurshidKc010** [comment]
Thanks for the response, we were able to fix this by changing the series for the shoulder shadow motor to the right one. The arm we are using is wx200 only but during the firmware updation, we changed the ID of the waist motor to 8, which caused the misunderstanding.

**Comment by MurshidKc010** [comment]
Thanks one more time
