### ISSUE TITLE
[Bug]: Not able to calibrate the plane of RViz simulator

### ISSUE THREAD

**Issue by MurshidKc010** [Interbotix/interbotix_ros_manipulators#114]
### What happened?

So we launched the actual arm through RViz but the problem is simulation is not same as that of the physical arm, for example in the sleep position it is showing like this in the RVIz, ideally in the simulator also it should come to the sleep position. Could you please help in this?
![Rviz simulation](https://github.com/Interbotix/interbotix_ros_manipulators/assets/143523422/65221743-02aa-4b4e-87ea-53dc9ae5f414)

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Distro

ROS 1 Noetic

### Additional Info

So in your documentation for wx 200, it shows the series for servo motors like this
![default_sevo_config](https://github.com/Interbotix/interbotix_ros_manipulators/assets/143523422/874be481-7bdd-49bc-a4a2-512295b52ab3)
But while connecting through the Dynamixel wizard, it shows like this
![Screenshot from 2023-09-01 15-57-42](https://github.com/Interbotix/interbotix_ros_manipulators/assets/143523422/88a7aa6e-acd3-400b-b106-66d8cfaba7be)
Ideally what should we select the series for the servo motors, I think like that this might cause this problem

**Comment by LSinterbotix** [comment]
Could you check that all of the motors on your arm match the model in the Default Servo Configurations table? The motors' models are displayed on their faces.

**Comment by MurshidKc010** [comment]
Thank you for the response, We changed the motor series for wrist angle to XL430-W250. After changing to this series it is not even detecting in the Dynamixel Wizard so we reverted the changes. But the model displayed on their face is XM430-W350 only. What do we have to do here? It would be really helpful if you could provide a response really quick

**Comment by LSinterbotix** [comment]
Try running a [firmware recovery](https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/#firmware-recovery) on the problem motor, setting its model to the one displayed on its face. Make sure only the one motor is plugged into the U2D2 when running through this process.

**Comment by MurshidKc010** [comment]
We already did this also, in Your WX-200 documentation shows that the motor series of wrist angle, wrist rotate, and gripper as XL430-W250 series but in the face it is showing XM430-W350 series for these motors, so we maintained these motors as XM430-W350 series. But still, the simulation is not happening properly, when the arm moves in one direction in the simulator it is moving in the opposite direction

**Comment by LSinterbotix** [comment]
Please provide a picture of the problem motor and the way it is mounted.

**Comment by MurshidKc010** [comment]
This is the rest pose of the arm in actual and in the simulator. Can you let us know why are they both different? Also we have figured out by changing the rpy and xyz values in the wx-200 URDF file, the calibration can be fixed. I hope we are correct here. Can you help us with the correct values of each motors and links so that we can fix this?
![gripper](https://github.com/Interbotix/interbotix_ros_manipulators/assets/143523422/6c148f8a-b504-475c-b6fa-aa3d7deeb07c)
![wrist_rotate](https://github.com/Interbotix/interbotix_ros_manipulators/assets/143523422/769e220c-db5d-4ca8-a058-ed99713b62ac)
![motor_face](https://github.com/Interbotix/interbotix_ros_manipulators/assets/143523422/4be77590-2553-40dd-abbd-3b6b4d7a18d2)
![calibration](https://github.com/Interbotix/interbotix_ros_manipulators/assets/143523422/05e55067-5a9f-4e1d-b306-de1df48a2499)

**Comment by MurshidKc010** [comment]
Any reply please?
Waiting for the response fro m yourside @LSinterbotix

**Comment by LSinterbotix** [comment]
Please contact our [technical support](https://www.trossenrobotics.com/contact.aspx) for assistance and reference this issue in your ticket.

**Comment by LSinterbotix** [comment]
The robot isn't actually "playing" chess, it's just moving the pieces around. The chessboard and chess pieces were used as a way to demonstrate the capabilities of our perception pipeline.

One of our customers did actually manage to get their robot to play against them. You can read more about it in [this discussion](https://github.com/orgs/Interbotix/discussions/6).

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
