### ISSUE TITLE
Chess code to play with robo arm with chess coordinates

### ISSUE THREAD

**Issue by kethan637** [Interbotix/interbotix_ros_manipulators#125]
### Question

Hi Actually we are working on the interboix robot arm widow x 200 playing the full chess game.so my request is to send  the actual code file for reference to work on it so please help us with the actual code .

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
We do not have the code that you are referring to. It was likely a modification of one of the [perception scripts](https://github.com/Interbotix/interbotix_ros_manipulators/tree/main/interbotix_ros_xsarms/interbotix_xsarm_perception/scripts) used to demonstrate our pointcloud-based perception pipeline.
