### ISSUE TITLE
[Bug]: It doesn't launch the with Gazebo the command ros2 launch interbotix_xsarm_moveit xsarm_moveit.launch.py robot_model:=rx200 hardware_type:=gz_classic

### ISSUE THREAD

**Issue by RodrigoMA170393** [Interbotix/interbotix_ros_manipulators#126]
### What happened?

The simulation launches the Rviz, but not the Gazebo simulation, I expected that the Gazebo simulation was launched as well

### Robot Model

rx200

### Operating System

Ubuntu 22.04

### ROS Distro

ROS 2 Humble

### Steps To Reproduce

Just launched "ros2 launch interbotix_xsarm_moveit xsarm_moveit.launch.py robot_model:=rx200 hardware_type:=gz_classic"

### Relevant log output

```shell
[ERROR] [gzclient-4]: process has died [pid 22669, exit code -6, cmd 'gzclient'].
```

**Comment by LSinterbotix** [comment]
See if the fix mentioned here solves your issue:  https://github.com/Interbotix/interbotix_ros_manipulators/issues/81#issuecomment-1562118208
