### ISSUE TITLE
[Question]: Velocity and effort controllers

### ISSUE THREAD

**Issue by RodrigoMA170393** [Interbotix/interbotix_ros_manipulators#127]
### Question

How can I program velocity, or effort controllers ?

### Robot Model

rx200

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

**Comment by LSinterbotix** [comment]
Our arms support velocity and effort commands when in the `velocity` and `current` operating modes, respectively. How you build the controller for those commands is up to you. You can find a lot of helpful resources in the [ros2_control documentation](https://control.ros.org/foxy/index.html).

I'm closing this issue, but I'll answer any specific questions you have regarding implementation.
