### ISSUE TITLE
About ROS2 installation issue

### ISSUE THREAD

**Issue by kethan637** [Interbotix/interbotix_ros_manipulators#129]
### Question

Hi, I am not able to install the ros2 package humble in my ubuntu 22.04 I am getting error
main issue:

> [ERROR] Failed to build Interbotix Arm ROS 2 Packages.
> [ERROR] Interbotix Installation Failed!

--- stderr: dynamixel_workbench_toolbox                                                                                                                                                                    
/home/skethan/interbotix_ws/src/interbotix_ros_core/interbotix_ros_xseries/dynamixel_workbench_toolbox/src/dynamixel_workbench_toolbox/dynamixel_driver.cpp: In member function ‘bool DynamixelDriver::readRegister(uint8_t, uint16_t, uint16_t, uint32_t*, const char**)’:
/home/skethan/interbotix_ws/src/interbotix_ros_core/interbotix_ros_xseries/dynamixel_workbench_toolbox/src/dynamixel_workbench_toolbox/dynamixel_driver.cpp:776:11: warning: ISO C++ forbids variable length array ‘data_read’ [-Wvla]
  776 |   uint8_t data_read[length];
      |           ^~~~~~~~~
/home/skethan/interbotix_ws/src/interbotix_ros_core/interbotix_ros_xseries/dynamixel_workbench_toolbox/src/dynamixel_workbench_toolbox/dynamixel_driver.cpp: In member function ‘bool DynamixelDriver::syncWrite(uint8_t, uint8_t*, uint8_t, int32_t*, uint8_t, const char**)’:
/home/skethan/interbotix_ws/src/interbotix_ros_core/interbotix_ros_xseries/dynamixel_workbench_toolbox/src/dynamixel_workbench_toolbox/dynamixel_driver.cpp:1012:11: warning: ISO C++ forbids variable length array ‘multi_parameter’ [-Wvla]
 1012 |   uint8_t multi_parameter[4*data_num_for_each_id];
      |           ^~~~~~~~~~~~~~~
---
Finished <<< dynamixel_workbench_toolbox [3.65s]
Starting >>> interbotix_xs_driver
--- stderr: interbotix_common_modules                                                                                                                                                         
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< interbotix_common_modules [5.00s]
Starting >>> interbotix_common_toolbox
Finished <<< interbotix_common_toolbox [1.83s]                                                                                                                                                    
Finished <<< interbotix_xs_driver [5.67s]                                                                                                                                                          
Finished <<< interbotix_tf_tools [14.0s]                                                                                                                                                                
--- stderr: interbotix_moveit_interface_msgs                                                                                                                       
Traceback (most recent call last):
  File "/opt/ros/humble/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 8, in <module>
    from rosidl_generator_py import generate_py
ImportError: cannot import name 'generate_py' from 'rosidl_generator_py' (/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_generator_py/__init__.py)
gmake[2]: *** [interbotix_moveit_interface_msgs__py/CMakeFiles/interbotix_moveit_interface_msgs__py.dir/build.make:152: rosidl_generator_py/interbotix_moveit_interface_msgs/_interbotix_moveit_interface_msgs_s.ep.rosidl_typesupport_fastrtps_c.c] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:590: interbotix_moveit_interface_msgs__py/CMakeFiles/interbotix_moveit_interface_msgs__py.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< interbotix_moveit_interface_msgs [18.0s, exited with code 2]
Aborted  <<< interbotix_xs_msgs [18.4s]                                                                                  
Aborted  <<< moveit_visual_tools [41.2s]                                   
                                  
Summary: 6 packages finished [42.6s]
  1 package failed: interbotix_moveit_interface_msgs
  2 packages aborted: interbotix_xs_msgs moveit_visual_tools
  4 packages had stderr output: dynamixel_workbench_toolbox interbotix_common_modules interbotix_moveit_interface_msgs moveit_visual_tools
  16 packages not processed
**

> [ERROR] Failed to build Interbotix Arm ROS 2 Packages.
> [ERROR] Interbotix Installation Failed!

**

### Robot Model

wx200

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

**Comment by LSinterbotix** [comment]
Are you using any kind of Python virtual environment?

**Comment by kethan637** [comment]
Noo I am not using any virtual environment

**Comment by LSinterbotix** [comment]
I am unable to reproduce this issue on a fresh install. Searching for this error reveals [this StackOverflow post](https://stackoverflow.com/questions/72752937/ros2-importerror-cannot-import-name-generate-py-from-rosidl-generator-py). See if any of the fixes mentioned there solve your issue.

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.

**Comment by kethan637** [comment]
No issue
