### ISSUE TITLE
[Bug]: Kinematics plugin not loaded

### ISSUE THREAD

**Issue by m-elwin** [Interbotix/interbotix_ros_manipulators#133]
### What happened?

When the moveit gui is loaded in rviz, there is no marker to manipulate the end-effector of the robot.

The move_group node issues the following warning

`[move_group-1] [WARN] [1698718212.215785560] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!`

This bug is due to what I believe is a change between `humble` and `iron`. In `iron` the kinematics configuration is now namespaced under `robot_description_kinematics`

### Robot Model

px100

### Operating System

Ubuntu 22.04

### ROS Distro

Other (Describe in "Additional Info")

### Steps To Reproduce

iron

**Comment by LSinterbotix** [comment]
Fixed for Iron in #134.
