### ISSUE TITLE
[Question]: Gripper control for wx200 ARM

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#139]
### Question

Hi Team,
We are using an Interbotix WX 200 arm. For that, we need to control the gripper.
How to control the gripper? 

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
If you are using the Python-ROS API, you can use the gripper module's [open and close methods](https://github.com/Interbotix/interbotix_ros_toolboxes/blob/0c739cdab1dbab03d79e752b43fa3db14d5bb15e/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/gripper.py#L75-L83). See an example of this [here](https://github.com/Interbotix/interbotix_ros_manipulators/blob/main/interbotix_ros_xsarms/examples/python_demos/gripper_control.py). The Python-ROS API expects that the gripper motor is set to the `pwm` or `current` [operating mode](https://github.com/Interbotix/interbotix_ros_manipulators/blob/341878954d92c7049d74eb8df2653f8012ea9dd1/interbotix_ros_xsarms/interbotix_xsarm_control/config/modes.yaml#L11). In these operating modes, joint commands sent to the gripper will produce effort, either closing or opening the gripper depending on the command's sign.

If you are using MoveIt, the gripper is in `linear_position` [operating mode](https://github.com/Interbotix/interbotix_ros_manipulators/blob/341878954d92c7049d74eb8df2653f8012ea9dd1/interbotix_ros_xsarms/interbotix_xsarm_moveit/config/modes.yaml#L11). Commands given to the gripper joint will set the corresponding linear position of the gripper fingers.

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
