### ISSUE TITLE
About the size of screw for the gripper

### ISSUE THREAD

**Issue by kethan637** [Interbotix/interbotix_ros_manipulators#145]
### Question

Can you please say where we can find the size of the screw for the gripper?
->I need the size of the screw from cartridge to gripper I need size of screw so please help me with that.

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
Please send a picture of the screw you're asking about.

If you're asking about the carriage screw shown in the picture below, it is M2x14.

![gripper_carriage_screw](https://github.com/Interbotix/interbotix_ros_manipulators/assets/85308904/8262b0b6-7ba2-4368-a3ea-698fbf664bd8)

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
