### ISSUE TITLE
[Question]: Is it currently possible to obtain image information from a specific viewpoint during Gazebo simulation?

### ISSUE THREAD

**Issue by GracefulMan** [Interbotix/interbotix_ros_manipulators#147]
### Question

Because I want to obtain image view during simulation, but I can't find the corresponding interface, hence the question.

### Robot Model

wx250s

### Operating System

Ubuntu 20.04

### ROS Version

ROS 2 Galactic

**Comment by LSinterbotix** [comment]
Check the Gazebo tutorial [here](https://classic.gazebosim.org/tutorials?tut=ros_gzplugins#Camera) on adding a camera to a scene using the Gazebo ROS camera plugin.
