### ISSUE TITLE
[Question]: Can the WX200 arm draw a human sketch

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#149]
### Question

We are using a WX200 arm. I want to know if this arm will be able to draw the human sketch or not. If possible, tell me the solution.

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
You should be able to make the arm follow arbitrary 2D trajectories by providing a series of end-effector poses. There are many steps required to accomplish this task, but I can only speak to providing pose goals to the robot.

### [Interbotix Python-ROS API](https://docs.trossenrobotics.com/interbotix_xsarms_docs/python_ros_interface.html)

The Interbotix Python-ROS API provides the ability to execute trajectories in Cartesian space using the [set_ee_cartesian_trajectory method](https://github.com/Interbotix/interbotix_ros_toolboxes/blob/main/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/arm.py#L263) of the [InterbotixArmXSInterface class](https://github.com/Interbotix/interbotix_ros_toolboxes/blob/main/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/arm.py#L38). Take a look at the [ee_cartesian_trajectory.py demo](https://github.com/Interbotix/interbotix_ros_manipulators/blob/main/interbotix_ros_xsarms/examples/python_demos/ee_cartesian_trajectory.py) for usage details.

### [MoveIt](https://ros-planning.github.io/moveit_tutorials/)

* [MoveIt Config Package Docs](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros1_packages/moveit_motion_planning_configuration.html)
* [MoveIt Interface & API Package Docs](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros1_packages/moveit_interface_and_api.html)

MoveIt provides the ability to plan and execute a trajectory through a series of points in the Cartesian space. You can base your code off of our MoveIt Python API tutorial's [plan_cartesian_path function](https://github.com/ros-planning/moveit_tutorials/blob/482dc9db944c785870274c35223b4d06f2f0bc90/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py#L247).
