### ISSUE TITLE
Incorrect config for RX150

### ISSUE THREAD

**Issue by Serafadam** [Interbotix/interbotix_ros_manipulators#15]
Hi, I just launched RX150, and the config for it is incorrect, since it contains wrong number of motors, I copied the config from rx200 and it works nicely.

**Comment by swiz23** [comment]
Can you post a picture of the robot you received?

**Comment by Serafadam** [comment]
Ah, sorry, that was some internal mixup about the robot type that we had. Everything is as it should be ;)
