### ISSUE TITLE
[Question]: Gripper customization for chess-playing robot

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#150]
### Question

We are using a WX200 arm. For that, we need grippers for playing chess. Send me all the available grippers to pick and place chess pieces. I also need the stl file of the gripper. We are using a 16x16 chess board, and for that, we need a gripper that should not disturb the other chess pieces while picking and placing them. 

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
You can find our documentation on how to customize the gripper [here](https://docs.trossenrobotics.com/interbotix_xsarms_docs/getting_started/customized_grippers.html).

The gripper finger STL can be found at [interbotix_ros_xsarms/interbotix_xsarm_descriptions/meshes/wx200_meshes/wx200_9_gripper_finger.stl](https://github.com/Interbotix/interbotix_ros_manipulators/blob/341878954d92c7049d74eb8df2653f8012ea9dd1/interbotix_ros_xsarms/interbotix_xsarm_descriptions/meshes/wx200_meshes/wx200_9_gripper_finger.stl)
