### ISSUE TITLE
Reinforcement Learning[Question]: 

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#154]
### Question

Is reinforcement learning possible on the Widowx200 robotic arm? Currently, we are using this arm for playing chess. If it is possible, give some ideas on how to do it.

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by kethan637** [comment]
link is showing 404 not found

**Comment by LSinterbotix** [comment]
The second link was bad. It has been updated: https://github.com/google-deepmind/mujoco_menagerie
