### ISSUE TITLE
[Question]: Tic Tac Toe Game 

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#156]
### Question

Is the Tic Tac Toe Game possible with a WX200 robotic arm? If possible, give some links.

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
I don't know of anyone that has done a game of tic tac toe with our arms, but the arm should be able to do whatever you program it to do.

It can be as simple as picking up pieces and placing them in known/pre-programmed locations, or as complicated as doing visual-perception-based processing to get those pick/place locations. I can't speak to the game logic, but I'm sure you can find resources for it online.

This is more of an application question so I won't be able to help you too much here. I'm happy to answer any specific questions you have on the usage of the arms.

Closing.
