### ISSUE TITLE
[Bug]: Gazebo doesn't launch using  xsarm_control.launch.py

### ISSUE THREAD

**Issue by RodrigoMA170393** [Interbotix/interbotix_ros_manipulators#157]
### What happened?

When trying to run the simulation of xsarm_control.launch.py using the Gazebo hardware interface, it doesn't launch Gazebo.

### Robot Model

wx200

### Operating System

Ubuntu 22.04

### ROS Distro

ROS 2 Humble

### Steps To Reproduce

Run the command:
ros2 launch interbotix_xsarm_control xsarm_control.launch.py robot_model:=wx200 use_sim:=true hardware_type:=gz_classic

### Relevant log output

```shell
[INFO] [launch]: All log files can be found below /home/rodrigo/.ros/log/2024-01-23-13-04-05-727435-rodrigo-Alienware-m15-R4-22186
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [xs_sdk_sim.py-1]: process started with pid [22188]
[INFO] [robot_state_publisher-2]: process started with pid [22190]
[INFO] [rviz2-3]: process started with pid [22192]
[xs_sdk_sim.py-1] Unknown tag "ros2_control" in /robot[@name='wx200']
[xs_sdk_sim.py-1] [INFO] [1706036646.450234961] [interbotix_xs_sdk.xs_sdk_sim]: Loaded motor configs from `/home/rodrigo/interbotix_ws/install/interbotix_xsarm_control/share/interbotix_xsarm_control/config/wx200.yaml`.
[xs_sdk_sim.py-1] [INFO] [1706036646.451378534] [interbotix_xs_sdk.xs_sdk_sim]: Loaded mode configs from `/home/rodrigo/interbotix_ws/install/interbotix_xsarm_control/share/interbotix_xsarm_control/config/modes.yaml`.
[xs_sdk_sim.py-1] [INFO] [1706036646.451650950] [interbotix_xs_sdk.xs_sdk_sim]: The operating mode for the 'all' group was changed to 'position'.
[xs_sdk_sim.py-1] [INFO] [1706036646.451888443] [interbotix_xs_sdk.xs_sdk_sim]: The operating mode for the 'arm' group was changed to 'position'.
[xs_sdk_sim.py-1] [INFO] [1706036646.457478142] [interbotix_xs_sdk.xs_sdk_sim]: Interbotix 'xs_sdk_sim' node is up!
```

### Additional Info

![image](https://github.com/Interbotix/interbotix_ros_manipulators/assets/115194213/f05381ad-9a9b-4f5a-a391-53d16f12413b)
![image](https://github.com/Interbotix/interbotix_ros_manipulators/assets/115194213/1e3c106c-40e3-4727-abae-e8253e4de3aa)

**Comment by LSinterbotix** [comment]
A few things:

- The xsarm_control package does not launch Gazebo
- Setting the use_sim arg to true switches to the use of a simulated DYNAMIXEL driver
- To use Gazebo, you can check out the [xsarm_sim package](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros2_packages/simulation_configuration.html)

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
