### ISSUE TITLE
[Question]: Interbotix arm in Unity Environment

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#159]
### Question

Hi Team,
We are using wx200 interbotix arm. Is our wx200 arm can be imported in Unity Environment. like ROS or Gazebo.

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
Unfortunately we do not have a Unity simulation setup for our Interbotix arms and we do not have plans to add one at this time.

The [Unity Robotics Hub](https://github.com/Unity-Technologies/Unity-Robotics-Hub) seems like a good place to start - specifically the [ros_unity_integration](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/README.md) and [urdf_tutorial](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_tutorial.md) tutorials.
