### ISSUE TITLE
Reinforcement Learning [Question]: 

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#160]
### Question

Hi Team,
Is reinforcement learning possible in the Interbotix wx200 arm.?
I want to do RL in the wx200 arm only. I'm not using any other arm apart from the WX200. So if it is possible with the WX200 arm, we will continue with reinforcement learning, or else we will look at the project without reinforcement learning.
We just want an answer, whether it is possible or not.

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
As stated in #154 and #155, we do not know of a reinforcement learning environments for the wx200. However, there is a vx300s MuJoCo model that can be used as a basis for a new wx200 MuJoCo model. See https://github.com/Interbotix/interbotix_ros_manipulators/issues/155#issuecomment-1893989554 for details. Closing as duplicate.
