### ISSUE TITLE
[Question]: Lack of Xarm package?

### ISSUE THREAD

**Issue by caijun199702** [Interbotix/interbotix_ros_manipulators#162]
### Question

following the instuction of "ROS 1 setup software setup" and input the following commands without any error:
sudo apt install curl
curl 'https://raw.githubusercontent.com/Interbotix/interbotix_ros_manipulators/main/interbotix_ros_xsarms/install/amd64/xsarm_amd64_install.sh' > xsarm_amd64_install.sh
chmod +x xsarm_amd64_install.sh
./xsarm_amd64_install.sh -d noetic

As I input:
source /opt/ros/$ROS_DISTRO/setup.bash
source ~/interbotix_ws/devel/setup.bash
rospack list | grep interbotix
to check the install result, It prints:
dynamixel_workbench_toolbox /home/caijun/interbotix_ws/src/interbotix_ros_core/interbotix_ros_xseries/dynamixel_workbench_toolbox
interbotix_common_modules /home/caijun/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_common_toolbox/interbotix_common_modules
interbotix_landmark_modules /home/caijun/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_common_toolbox/interbotix_landmark_modules
interbotix_moveit_interface /home/caijun/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_common_toolbox/interbotix_moveit_interface
interbotix_perception_modules /home/caijun/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_perception_toolbox/interbotix_perception_modules
interbotix_tf_tools /home/caijun/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_common_toolbox/interbotix_tf_tools
interbotix_xs_modules /home/caijun/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_xs_toolbox/interbotix_xs_modules
interbotix_xs_msgs /home/caijun/interbotix_ws/src/interbotix_ros_core/interbotix_ros_xseries/interbotix_xs_msgs
interbotix_xs_ros_control /home/caijun/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_xs_toolbox/interbotix_xs_ros_control
interbotix_xs_rviz /home/caijun/interbotix_ws/src/interbotix_ros_toolboxes/interbotix_xs_toolbox/interbotix_xs_rviz
interbotix_xs_sdk /home/caijun/interbotix_ws/src/interbotix_ros_core/interbotix_ros_xseries/interbotix_xs_sdk

Couldnot find any interbotix_xsarm_* series package. what's wrong?

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
What are the contents of your ~/interbotix_ws/src/ directory? The installation script may have failed somehow. You can remove or rename the interbotix_ws directory and try running the script again.

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
