### ISSUE TITLE
[Question]: Tic Tac Toe Game

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#163]
### Question

Hi Team,
We are using an Interbotix WX 200 arm. With this, we have to play a tic-tac-toe game in a virtual simulation. So which environment do we have to choose for virtual simulation? Also, send some links to refer to if our arm has already played the tic-tac-toe game.

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
We only have simulation configuration for Gazebo classic. See the [xsarm_gazebo package](https://github.com/Interbotix/interbotix_ros_manipulators/tree/main/interbotix_ros_xsarms/interbotix_xsarm_gazebo) and [docs](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros1_packages/gazebo_simulation_configuration.html) for details. As stated in https://github.com/Interbotix/interbotix_ros_manipulators/issues/156#issuecomment-1896205488, we're not aware of anyone that has done tic tac toe using our arms.
