### ISSUE TITLE
[Question]: ROS Development studio

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#164]
### Question

Hi team,
How to install ROS Development Studio in local. Are any documents or links available?

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
> ROS Development Studio

This seems to be a project run by [The Construct](https://www.theconstructsim.com/the-ros-development-studio-by-the-construct/). I would read through their documentation to learn more. Closing as unrelated.
