### ISSUE TITLE
[Question]: Use an open Manipulator to play tic-tac-toe by Clarkson University Team

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#165]
### Question

Hi team,
Use an open manipulator to play tic-tac-toe with the Clarkson University team. For this video, click here: https://youtu.be/v1IqtPPIWyc?si=4wO96NrDe65Ir18u.

Where can I find the code? We are also doing the same project. So if there are any GitHub projects, they will be useful.

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
The [OpenMANIPULATOR-X](https://emanual.robotis.com/docs/en/platform/openmanipulator_x/overview/) is an arm made by Robotis. I would refer to their documentation and the video you attached for more information.

That project is unrelated to the Interbotix X-Series arms and our software. Closing as unrelated.
