### ISSUE TITLE
[Question]: Gazebo Simulation

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#166]
### Question

Hi Team,
How can we use this simulation link: https://gazebosim.org/home?

We are planning to play a tic-tac-toe game on the WX200 robotic arm. In the gazebo, we imported our arm. But the tic-tac-toe game we are planning to create using this link: https://gazebosim.org/home. So any idea how this setup will be created? Is this the right way? Also, once we create the tic-tac-toe game setup, how can we import it into the Gazebo simulation?

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
As mentioned in https://github.com/Interbotix/interbotix_ros_manipulators/issues/163#issuecomment-1927488495, we provide the xsarm_gazebo package to configure our arms to be simulated in Gazebo. See my comment there for details.

> once we create the tic-tac-toe game setup, how can we import it into the Gazebo simulation

This depends on how you want to do things. One way to go about creating your game is to create a custom model. See [Gazebo's tutorials](https://classic.gazebosim.org/tutorials) on how to do so. The [model editor](https://classic.gazebosim.org/tutorials?tut=model_editor) and [build a world](https://classic.gazebosim.org/tutorials?cat=build_world) tutorials might be useful to you specifically.
