### ISSUE TITLE
[Bug]: Gripper pressure

### ISSUE THREAD

**Issue by rouzinho** [Interbotix/interbotix_ros_manipulators#173]
### What happened?

Hi !

I am running an experiment with my robot and I encountered some problem during grasping. I am setting the pressure and closing the gripper with :
`self.bot.gripper.set_pressure(0.7)`
`self.bot.gripper.close()`
The problem is the gripper does not close completely and stays half way opened. When I began my experiment, I used 0.4 for the pressure value and it was working well. I have been increasing the value since to close the gripper completely when there is no object, otherwise the gripper is just grasping the object.
I 'm wondering if I am not damaging the motor gripper by proceeding this way.

Thanks for your help !

### Robot Model

px150

### Operating System

Ubuntu 20.04

### ROS Distro

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
Increasing the gripper pressure should not damage your motor assuming you're also not dramatically increasing the PWM limits.

You gripper carriages may be degrading with use. We provide [CAD files](https://docs.trossenrobotics.com/interbotix_xsarms_docs/getting_started/customized_grippers.html#cad-files) for these if you'd like to print replacements. You may also try lubricating the carriage rails with a PLA-safe lubricant.
