### ISSUE TITLE
Gazebo SimulationQuestion]: 

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#175]
### Question

Hi Team,
We are using interbotix wx200 arm . in that Gazebo simulation how do i import live video feed inside Gazebo environment. We are using intel real sense camera. I want whatever capturing that to be displayed  inside gazebo environment

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
This question is unrelated to the Interbotix manipulators software. Please ask questions like these on the [robotics StackExchange](https://robotics.stackexchange.com/).

[This package](https://github.com/pal-robotics/realsense_gazebo_plugin) seems like a useful first step. You can see how we simulate cameras in our LoCoBots research rovers [here](https://github.com/Interbotix/interbotix_ros_rovers/blob/b1b5a180d31316636c58521419e0405eb5c0e249/interbotix_ros_xslocobots/interbotix_xslocobot_descriptions/urdf/pan_and_tilt.urdf.xacro#L143-L183) as well.
