### ISSUE TITLE
[Question]: Requesting permission to use images from the documentation in my thesis

### ISSUE THREAD

**Issue by AbishekNP** [Interbotix/interbotix_ros_manipulators#178]
### Question

Hello,
I've been conducting research on the ViperX 300s model and I wish to include an image from this website in my thesis:
https://docs.trossenrobotics.com/interbotix_xsarms_docs/specifications/vx300s.html

I've given proper citations to this website and acknowledged the resource. May I please know if I have your permission to use an image from this site?

Thank You

### Robot Model

vx300s

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
Our software and documentation is distributed under the BSD-3-Clause license. As long as you're adhering to the terms and conditions described there, we have no issue with redistribution.

Feel free to [cite us](https://github.com/Interbotix/interbotix_ros_manipulators?tab=readme-ov-file#citing) in your thesis too!
