### ISSUE TITLE
Competibility with arm from Ufactory

### ISSUE THREAD

**Issue by tarasborov** [Interbotix/interbotix_ros_manipulators#18]
A while ago I have purchased the xArm7 from Ufactory. Can I use your repository in this case or is your repo is compatible only with arms sold by Trossen Robotics?

**Comment by LSinterbotix** [comment]
Hi @tarasborov! Yes, you should be able to use the [uxarms packages](https://github.com/Interbotix/interbotix_ros_manipulators/tree/main/interbotix_ros_uxarms#interbotix-ufactory-xarm-ros-packages) from this repo for arms bought from Ufactory. Just note that we no longer support the platform.

**Comment by tarasborov** [comment]
Thanks for your answer!
