### ISSUE TITLE
Gazebo Simulation

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#185]
### What happened?

Hi Team,
We have a working tic-tac-toe game in Python. How can we use that in Gazebo simulation? What are all the steps to import that working code in gazebo?

### Robot Model

wx200

### Operating System

Ubuntu 22.04

### ROS Distro

ROS 2 Humble

**Comment by lukeschmitt-tr** [comment]
See https://github.com/Interbotix/interbotix_ros_manipulators/issues/167 or the [Gazebo tutorials](https://classic.gazebosim.org/tutorials) for answers to these questions.
