### ISSUE TITLE
[Question]: RVIZ arm pose dose not match the real-world arm (self-made) pose

### ISSUE THREAD

**Issue by evallhq** [Interbotix/interbotix_ros_manipulators#186]
### Question

Hope this message finds you well!

Thank you very much for your open-source resources. I assembled a vx300s by purchasing DYNAMIXEL motors and printing 3D arm structures. When I followed the documentation [https://docs.trossenrobotics.com/interbotix_xsarms_docs/index.html](url) to configure the software and hardware, I found that the posture of the vx300s arm in RVIZ did not match the posture of the real-world vx300s arm. May I ask what the reasons may be and how I should solve it?

<img width="1329" alt="image" src="https://github.com/Interbotix/interbotix_ros_manipulators/assets/89585894/22a4aeeb-c22c-41d5-94ae-027814742947">

As far as I know, it is possible that I did not carefully check whether the zero position of each motor was aligned accurately when assembling the robotic arm. Do I need to dismantle the robotic arm and inspect each motor? Or can we perform pose matching by changing the sleep position parameter in the `motor_config.yaml` file of vx300s?

Thank you very much. Looking forward to your comments.

### Robot Model

vx300s

### Operating System

Ubuntu 18.04

### ROS Version

ROS 1 Melodic

**Comment by lukeschmitt-tr** [comment]
Apologies, but we do not support the reverse engineering of our manipulators. I'm sure you'd understand.
