### ISSUE TITLE
Obstacle Avoidance

### ISSUE THREAD

**Issue by kethan637** [Interbotix/interbotix_ros_manipulators#188]
### Question

So i am have interbotix wx200 arm so how can do obstacle avoidance for the arm where can I find those tasks and how to do can you send me the reference so that that could be help full for the your project
suppose it should be like if arm is going to pick some thing then human hand came in the middle so that it should stop that and go back and again after hand removed it should got o pick from there

### Robot Model

wx200

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

**Comment by lukeschmitt-tr** [comment]
We do not provide the ability for workspace scene reconstruction. However, there are open source tools available like [MoveIt](https://moveit.picknik.ai/main/index.html) that allow for such behavior. Please see MoveIt's documentation on its [Planning Scene Monitor](https://moveit.picknik.ai/main/doc/concepts/planning_scene_monitor.html) for details.

I would recommend [looking for similar questions](https://robotics.stackexchange.com/search?q=planning+scene+monitor) (or asking your own [new question](https://robotics.stackexchange.com/questions/ask)) on the [robotics StackExchange](https://robotics.stackexchange.com/).
