### ISSUE TITLE
[Question]: 3D object detection and avoidance using ROS2

### ISSUE THREAD

**Issue by shoryasiddharth** [Interbotix/interbotix_ros_manipulators#194]
### Question

Hi, 
I am working on a TicTacToe game in which x and o are square-pieced. My goal is to let it play tic tac toe, for that it should be able to pick and place pieces from outside or inside the tictactoe board. It should also avoid objects if some objects come in the path of the arm's movement.
I am also using the vision kit (Intel Real Sense D415).
I want to use the point clouds to detect the square pieces and their positions (x, y, z).
I tried perception and the pointcloud filters but does not work that well. 
I need suggestions or help from someone who already did object detection using point clouds.
I also tried NVIDIA-TAO pointpillars, but there is something wrong with their example notebooks. The model's docker image does not contain a package which is not available publically.

### Robot Model

wx200

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

**Comment by lukeschmitt-tr** [comment]
This is more of a question for our Discussions forum. I see that you've [already posted this question](https://github.com/orgs/Interbotix/discussions/49) there.

Closing.
