### ISSUE TITLE
Wx250s controllers

### ISSUE THREAD

**Issue by kethan637** [Interbotix/interbotix_ros_manipulators#198]
### Question

For model wx250. Bot.gripper.grasp and release are rotating the pitch and roll
can you say the what are commands for those wx250s arm gripper controls.

### Robot Model

wx250s

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

**Comment by lukeschmitt-tr** [comment]
In your question, you are asking about the `wx250`, but in the Robot Model field, you list the `wx250s`. The ID of the gripper motor is 8 on the `wx250`. ID 8 on the `wx250s` is the wrist_rotate joint. If you are launching the wrong robot, gripper commands will indeed rotate the wrist, causing this behavior you are seeing. Please provide the launch command you are using.

**Comment by kethan637** [comment]
I need answer for wx250s only what is the command for opening and closing gripper in wx250s

**Comment by kethan637** [comment]
bot.gripper.grasp()

**Comment by lukeschmitt-tr** [comment]
> bot.gripper.grasp()

That is the correct command. However, you may be launching the wrong robot model which would cause this behavior. Make sure that the robot you have, the robot_model launch arg, and the robot_model arg you're giving to the Python API are all correct.

Please provide the control package launch command you're using. If you're running the wx250s, it should be:

```bash
ros2 launch interbotix_xsarm_control xsarm_control.launch.py robot_model:=wx250s
```

If you launch it with `wx250` instead, you'll see the "wrist joint as gripper joint" issue you describe.

**Comment by lukeschmitt-tr** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
