### ISSUE TITLE
[Enhancement]: Can I pause the arms movement inbetween and play it in between 

### ISSUE THREAD

**Issue by shoryasiddharth** [Interbotix/interbotix_ros_manipulators#201]
### Describe the solution you'd like

I am working on a usecase where an arm can avoid objects in my case it is a hand. I want it to stop when a hand is in  the way and resume when it out of the way.
Is it there?

### Platform

xsarm - wx200

### Is your feature request related to a problem? Please describe.

yes

**Comment by lukeschmitt-tr** [comment]
There is no way to do this currently. You may want to look into something like the [MoveIt2 Planning Scene Monitor](https://moveit.picknik.ai/main/doc/concepts/planning_scene_monitor.html) to accomplish this. The Monitor can build a representation of the robot's workspace.

Closing.
