### ISSUE TITLE
[Bug]: xsarm_description launching two rviz nodes with same name

### ISSUE THREAD

**Issue by irisxu02** [Interbotix/interbotix_ros_manipulators#209]
### What happened?

Hi!

I noticed that two rviz nodes are being launched when running xsarm_description.launch.py directly from the cmd line. This is not affecting viewing the robot in rviz or showing up in instances where xsarm_description.launch.py is used by other launch files (eg. only one rviz node would be launched by running `ros2 launch interbotix_xsarm_sim xsarm_gz_classic.launch.py robot_model:=vx300s`). 

Just wanted to make a note of the fact, although nothing is really breaking :shrug: 

### Robot Model

vx300s

### Operating System

Ubuntu 22.04

### ROS Distro

ROS 2 Humble

### Steps To Reproduce

`ros2 launch interbotix_xsarm_descriptions xsarm_description.launch.py robot_model:=vx300s use_joint_pub_gui:=true
`
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [1103600]
[INFO] [joint_state_publisher_gui-2]: process started with pid [1103602]
[INFO] [rviz2-3]: process started with pid [1103604]

`ros2 node list
`
WARNING: Be aware that are nodes in the graph that share an exact name, this can have unintended side effects.
/vx300s/robot_state_publisher
/vx300s/rviz2
/vx300s/rviz2
/vx300s/transform_listener_impl_60d16be5dd40

**Comment by lukeschmitt-tr** [comment]
Thanks for the report.

Seems like the [rviz2 Node launch_ros action](https://github.com/Interbotix/interbotix_ros_manipulators/blob/41746ab1ae56e7b4f99dbc3d9c73aeaadc3ab0b2/interbotix_ros_xsarms/interbotix_xsarm_descriptions/launch/xsarm_description.launch.py#L92) causes this. Not including this in the list of launch actions prevents both instances of rviz2 nodes from coming up. I would assume this is something with how RViz interacts with the ROS graph and not an issue with multiple rviz2 bringup.
