### ISSUE TITLE
MoveIt Pose and Orientation Planning Failures

### ISSUE THREAD

**Issue by autonomousTurtle** [Interbotix/interbotix_ros_manipulators#21]
### MoveIt Pose Failures

Hello! 

First off, thank you for all of the great info you are publishing into this community! 

**My question:**
I am attempting to follow your youtube video [here](https://www.youtube.com/watch?v=Z9s3hRYcIp0) - Interbotix Tutorials: X-Series Arms | Using The Interbotix MoveIt Interface ROS Package

Using unmodified files, and am running the moveit interface with your cpp gui using: 

`roslaunch interbotix_xsarm_moveit_interface xsarm_moveit_interface.launch robot_model:=wx250s use_fake:=true dof:=6 use_cpp_interface:=true
`
however, every time I press the Plan Pose or Plan Orientation buttons on the GUI, the result is not successful. Only the plan position is successful. 

Output on the terminal: 

[INFO] [1637679240.764232]: Desired end-effector pose: x[m]: 0.20, y[m]: 0.30, z[m] 0.30, roll[rad]: 0.00, pitch[rad]: 0.00, yaw[rad]: 0.00.
[ INFO] [1637679240.780846918]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1637679240.783235304]: Planner configuration 'interbotix_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1637679240.783705162]: interbotix_arm/interbotix_arm: Starting planning with 1 states already in datastructure
[ERROR] [1637679241.227466066]: interbotix_arm/interbotix_arm: Unable to sample any valid states for goal tree
[ INFO] [1637679241.227490468]: interbotix_arm/interbotix_arm: Created 1 states (1 start + 0 goal)
[ INFO] [1637679241.227500775]: No solution found after 0.443995 seconds
[ INFO] [1637679241.227512375]: Unable to solve the planning problem
[ WARN] [1637679241.227745975]: Fail: ABORTED: No motion plan found. No execution attempted.
[ WARN] [1637679241.227784206]: Skipping path because 0 points passed in.
[ INFO] [1637679241.227800708]: success: 0
[INFO] [1637679241.228001]: Planning EE pose was not successful.

Is there a step or config file I am missing? 

Thank you!

### Robot Model

wx250s, simulated

### Operating System

Ubuntu 20.04, ROS noetic

**Comment by LSinterbotix** [comment]
Hi @autonomousTurtle! Try setting [this parameter](https://github.com/Interbotix/interbotix_ros_manipulators/blob/4a1b2ec08ad6a99d23bf5db8e66370d7ac439dbb/interbotix_ros_xsarms/interbotix_xsarm_moveit/config/kinematics.yaml#L26) to `false` or commenting it out.

**Comment by autonomousTurtle** [comment]
> Hi @autonomousTurtle! Try setting [this parameter](https://github.com/Interbotix/interbotix_ros_manipulators/blob/4a1b2ec08ad6a99d23bf5db8e66370d7ac439dbb/interbotix_ros_xsarms/interbotix_xsarm_moveit/config/kinematics.yaml#L26) to `false` or commenting it out.

That did the trick. Thank you!
