### ISSUE TITLE
[Question]: In what file modifying the robot geometrical features when launching 'xsarm_moveit.launch.py'?

### ISSUE THREAD

**Issue by qcharmoillau** [Interbotix/interbotix_ros_manipulators#218]
### Question

Hello,

I want to simulate motions with the WX250s with different geometrical features, for example, with different link lengths, inertias, ... . But I do not know in what file I should change these features.

I firstly tried to modify the features in the `wx250s.urdf.xacro` from `/src/interbotix_ros_manipulators/interbotix_ros_xsarms/interbotix_xsarm_descriptions/urdf`, then I re-built the package and I launched a custom file which launches `xsarm_moveit.launch.py`. However, nothing had changed in the simulated robot.
Moreover, it seems that the `.srdf` file does not include any geometrical data.

So, what and where is the file in which I must write to modify these features?

### Robot Model

wx250s

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

**Comment by lukeschmitt-tr** [comment]
The URDF is the right file to edit in order to change things like the geometric and inertial properties of the robot.

I modified the should joint's origin and achieved the following result when launching:

```console
$ ros2 launch interbotix_xsarm_moveit xsarm_moveit.launch.py robot_model:=wx250s hardware_type:=fake
```

![image](https://github.com/user-attachments/assets/932fd1e3-9495-48ba-9278-cbe937f6080c)
