### ISSUE TITLE
[Question]: Some ros1 launch files in ros2 wrapper

### ISSUE THREAD

**Issue by Zhuomin-Zhou** [Interbotix/interbotix_ros_manipulators#29]
### Question

Hi,

When I was trying to **colcon build** the galactic wrapper, I noticed there were some ros1 launch files in there, which caused the failure of **colcon build**.
I am confused, could you give me some installation instructions?
Thanks in advance!

Min 

### Robot Model

wx250x

### Operating System

Ubuntu20.04

**Comment by LSinterbotix** [comment]
We are in the middle of porting our packages to ROS2 galactic. You may face some issues when using that branch. We are nearly finished porting all essential manipulator packages. Check out how to use at least the core packages in [this issue](https://github.com/Interbotix/interbotix_ros_core/issues/19).
