### ISSUE TITLE
[Bug]: [xs_sdk] groupSyncRead getdata failed

### ISSUE THREAD

**Issue by CRoIS1** [Interbotix/interbotix_ros_manipulators#31]
### What happened?

Tried to start the joystick control using the following command.

`roslaunch interbotix_xsarm_joy xsarm_joy.launch robot_model:=wx200`

During configuration I received this warning message. 

`[ WARN] [1654634938.647017794]: Couldn't set gain on joystick force feedback: Bad file descriptor`

Then gave this error repeatedly. upon startup 

`[ERROR] [1654634967.357863833]: [xs_sdk] [TxRxResult] There is no status packet!
[ERROR] [1654634967.358075128]: [xs_sdk] groupSyncRead getdata failed
[ERROR] [1654634967.358149498]: [xs_sdk] groupSyncRead getdata failed
[ERROR] [1654634967.358211590]: [xs_sdk] groupSyncRead getdata failed`

### Robot Model

rx200

### Operating System

Ubuntu 20.4

### Steps To Reproduce

Powered on pi and robot
Initiated joystick start command

### Relevant log output

```shell
[ERROR] [1654634967.357863833]: [xs_sdk] [TxRxResult] There is no status packet!
[ERROR] [1654634967.358075128]: [xs_sdk] groupSyncRead getdata failed
[ERROR] [1654634967.358149498]: [xs_sdk] groupSyncRead getdata failed
[ERROR] [1654634967.358211590]: [xs_sdk] groupSyncRead getdata failed
```

**Comment by LSinterbotix** [comment]
The `Couldn't set gain on joystick force feedback: Bad file descriptor` warning is meaningless and can be safely ignored.

Try following the steps outlined in the Troubleshooting Guide's [`Incorrect status packet`](https://www.trossenrobotics.com/docs/interbotix_xsarms/troubleshooting/index.html#incorrect-status-packet) section.
