### ISSUE TITLE
[Question]: Actual robot not responding but simulation on RViz does.

### ISSUE THREAD

**Issue by sbhambr1** [Interbotix/interbotix_ros_manipulators#34]
### Question

Why is the actual robot not responding when running the python demos (e.g. bartender.py)?

### Robot Model

px100

### Operating System

Ubuntu 20.04
ROS Noetic

### Anything Else

I am able to successfully run the python demos on simulation using the following commands:

`roslaunch interbotix_xsarm_control xsarm_control.launch robot_model:=px100 use_sim:=true`
`python3 bartender.py`

Unfortunately, when I run the commands for the actual robot (without the `use_sim` flag), there is no response on RVIZ and the actual robot. The terminal gives me no error too!

Here are the screenshots:

Running the command:  `roslaunch interbotix_xsarm_control xsarm_control.launch robot_model:=px100`
![image](https://user-images.githubusercontent.com/43840095/174117707-0fcd5a33-4dc0-4c45-96a4-957ec33bffb6.png)

Running the command: `python3 bartender.py`
![image](https://user-images.githubusercontent.com/43840095/174117556-9d208863-b5d0-4a77-8b8f-05c9e3187205.png)

Any help is appreciated, thanks!

**Comment by LSinterbotix** [comment]
I would suggest checking the topics `/command/joint_single`, `/command/joint_trajectory`, and `joint_states` for output. The px100 will probably be unable to complete the bartender script with the default values, so it's possible that the robot is just skipping over commands other than the ones issued by the `set_single_joint_position`.

**Comment by sbhambr1** [comment]
Hi, thanks for the quick response!
I was able to update the arguments for the commands to suit this robot and it worked flawlessly in the beginning. After a few runs, the mentioned issue occurred and the motors stopped working for the actual robot.

**Comment by LSinterbotix** [comment]
By "the mentioned issue", do you mean #35? If so, this can be closed in favor of that issue.

**Comment by sbhambr1** [comment]
Yes, thanks once again! I believe having #35 resolved first would be more helpful. Closing the issue till then.
