### ISSUE TITLE
rviz pose does not match with robot pose (initial install)

### ISSUE THREAD

**Issue by seth814** [Interbotix/interbotix_ros_manipulators#4]
I got through installation easily enough.
ran `roslaunch interbotix_xsarm_control xsarm_control.launch robot_model:=rx200`
Is there a setting I need to change or did someone not test stuff? :thinking: 

Rviz screenshot

![Screenshot from 2021-02-06 19-59-53](https://user-images.githubusercontent.com/17873279/107133527-2987c680-68b7-11eb-8483-f946dc2dde1e.png)

Reactor 200

![20210206_200418](https://user-images.githubusercontent.com/17873279/107133530-2b518a00-68b7-11eb-8cdf-7a03c89a68fc.jpg)

I tried running the example scripts, and well... It proceeded to crash into things.

**Comment by swiz23** [comment]
Ya,

The second thing you said - 'someone did not test stuff' :/

It looks like the shoulder motor ids need to be switched. In the picture you attached above, the shoulder motor that is visible should be ID'd Number 3. The shoulder motor on the other side (not viewable) should be ID'd Number 2. You can easily switch IDs using the Dynamixel Wizard 2.0 tool. See more at https://github.com/Interbotix/interbotix_ros_core/blob/main/interbotix_ros_xseries/interbotix_xs_sdk/TROUBLESHOOTING.md#dynamixel-wizard-20-tool.

**Comment by seth814** [comment]
Switched the ids on the motors for 2 and 3. We're back in business!

![Screenshot from 2021-02-08 21-20-40](https://user-images.githubusercontent.com/17873279/107306993-e151db00-6a53-11eb-99b9-fe91306c8b4b.png)
