### ISSUE TITLE
[Question]: controller not loading

### ISSUE THREAD

**Issue by flamboyantflower** [Interbotix/interbotix_ros_manipulators#45]
### Question

After inputting into the command line: roslaunch interbotix_xsarm_gazebo xsarm_gazebo.launch robot_model:=wx250 use_position_controllers:=true

I get:
[ERROR] [1660068076.184717276]: Could not load controller 'waist_controller' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1660068076.184754727]: Use 'rosservice call controller_manager/list_controller_types' to get the available types

### Robot Model

wx250

### Operating System

Ubuntu 20.04

### ROS Version

ROS1 Noetic

**Comment by LSinterbotix** [comment]
As mentioned in [#44](https://github.com/Interbotix/interbotix_ros_manipulators/issues/44#issuecomment-1208522107), you don't seem to have the joint_trajectory_controller package installed. Install it through its source, using apt, or using rosdep.
