### ISSUE TITLE
[Question]: Where do I put a python script file in order to execute it?

### ISSUE THREAD

**Issue by flamboyantflower** [Interbotix/interbotix_ros_manipulators#46]
### Question

So I am now able to send position commands to my gazebo simulated rx150, I would like to send position commands via a python script now. I wrote the script, and execute it in the terminal.

input to terminal:
rosrun rx150_control main.py

output:
[INFO] [1660247577.909809, 0.000000]: 1.0

but the simulated robot does not act on the command.

Is my script in the wrong location of the file tree?

### Robot Model

rx150

### Operating System

Ubuntu 20.04

### ROS Version

ROS1 Noetic

**Comment by LSinterbotix** [comment]
It doesn't matter where you keep the Python script as long as you can execute it using some method (which you seem to be able to do using `rosrun`).

I would make sure that you're publishing to the correct topic. Use the `rqt_graph` tool or the `rostopic` command to check if your node is connected to the right topics coming from Gazebo.

I would be happy to help further if you provide more details about your script and what you're trying to do with it.

**Comment by flamboyantflower** [comment]
hey thanks for looking at my question
here is the script
#!/usr/bin/env python3
import rospy
from std_msgs.msg import String


import rospy
from std_msgs.msg import Float64

def talker():
	pub = rospy.Publisher('/rx150/wrist_rotate_controller/command', Float64, queue_size=10)
	rospy.init_node('rx150_talker', anonymous=True)
	rate = rospy.Rate(10)
	while not rospy.is_shutdown():
		position = -1.0
		rospy.loginfo(position)
		pub.publish(position)
		rate.sleep()
		
if __name__ == '__main__':
	try:
		talker()
	except rospy.ROSInterruptException:
		pass

**Comment by LSinterbotix** [comment]
Your script works for me. I modified it to cycle the wrist_rotate position command between 1.0 and -1.0 and got the expected result below:

![rx150](https://user-images.githubusercontent.com/85308904/184249821-dd114b3a-4bef-4ab1-9e71-84f57460461e.gif)

![rosgraph](https://user-images.githubusercontent.com/85308904/184250097-d52ac73f-4be7-4faa-83b2-2631984c6dd5.png)

Is your Gazebo unpaused when you're running this script? Are you setting `robot_name` when launching the xsarm_gazebo package, or leaving it as the default (`robot_model`)?

**Comment by flamboyantflower** [comment]
I left the default robot model when launching and yes I did run rosservice call /gazebo/unpause_physics

**Comment by flamboyantflower** [comment]
fixed, had to change code from wrist_rotate_controller to wrist_angle_controller
