### ISSUE TITLE
[Bug]: Cannot connect to robot

### ISSUE THREAD

**Issue by kirstyellis** [Interbotix/interbotix_ros_manipulators#51]
### What happened?

I followed the installation instructions, but when I connect the USB cable to my computer, there is nothing to indicate that the connection has been detected, no change in /dev and no log in dmesg. This command returns nothing: ls /dev | grep ttyDXL

When I powered the robot, a red light on each motor flashed once, I am not sure if this is expected.

I also installed Dynamixel wizard and the scan doesn't return any results. 

Any ideas what could be wrong?

### Robot Model

Rx150

### Operating System

Ubuntu 20.04

### ROS Distro

ROS1 Noetic

**Comment by LSinterbotix** [comment]
I would first check the [Can't Find DYNAMIXEL ID](https://www.trossenrobotics.com/docs/interbotix_xsarms/troubleshooting/index.html#can-t-find-dynamixel-id) troubleshooting guide. Then see the steps below:

- It's possible that there's something wrong with the connection between the Power Hub and U2D2 or the U2D2 and your computer - check these connections, maybe even see if a different USB->MicroUSB cable fixes the issue.
- Does the U2D2 light up red when connected to your computer?

**Comment by kirstyellis** [comment]
Hi @LSinterbotix, thank you for your reply. I only tried with the cable that was shipped with the robot, I will try another. When I connect the robot to my computer there is no LED action on the U2D2.

**Comment by LSinterbotix** [comment]
No LED on the U2D2 would indicate a U2D2 failure or a bad connection to the computer. Let us know if the former is the case - we can ship you a replacement.

**Comment by kirstyellis** [comment]
I can confirm that after trying a different USB cable, the light on the U2D2 is now on and I can see the device in /dev.

Thank you for assisting with this!
