### ISSUE TITLE
No CameraInfo received on [/camera/color/camera_info]

### ISSUE THREAD

**Issue by hcdiekmann** [Interbotix/interbotix_ros_manipulators#52]
When launching the perception package to get the camera_link transform from the robot base_link with the AprilTag.

**Robot Model**
px100

**Operating System**
Ubuntu 20.04

**ROS Distro**
ROS2 Galactic

**Camera**
Intel RealSense D435

Steps To Reproduce
_ros2 launch interbotix_xsarm_perception xsarm_perception.launch.py robot_model:=px100 use_pointcloud_tuner_gui:=true use_armtag_tuner_gui:=true_

Result:
![image](https://user-images.githubusercontent.com/13176191/200552606-2e2d1fdb-b9fd-4980-a3f2-b17e97d9671a.png)

**Comment by LSinterbotix** [comment]
This should be fixed for Galactic in commit [c3d3dbf](https://github.com/Interbotix/interbotix_ros_manipulators/commit/c3d3dbfb5b90b3d5cca4c6607053e1211a5c7ad5). Feel free to reopen if not.

**Comment by hcdiekmann** [comment]
Works now, thank you
