### ISSUE TITLE
[Question]: Installation of Python API

### ISSUE THREAD

**Issue by krishanrana** [Interbotix/interbotix_ros_manipulators#60]
### Question

Hi, I have used catkin to build all my packages however am unsure how to get the required python API package installed. Should I invoke a manual pip install . or do you recommend another method? Thank you

### Robot Model

WX250s

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
Once your workspace is built, properly sourcing the ROS setup script and your Interbotix workspace's setup script will configure your `PYTHONPATH` environment variable to include the workspace's `devel/lib/python3/dist-packages` directory. See the ROS Wiki's [Managing Your Environment tutorial](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment#Managing_Your_Environment) for more details.

```console
$ printenv PYTHONPATH
$ source /opt/ros/noetic/setup.bash && printenv PYTHONPATH
/opt/ros/noetic/lib/python3/dist-packages
$ source ~/interbotix_ws/devel/setup.bash && printenv PYTHONPATH
/home/interbotix/interbotix_ws/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages
```

This enables any Python script run from that terminal to see the Python-ROS API's modules. 

The install script will append the sourcing commands to your `~/.bashrc` file.
