### ISSUE TITLE
[Bug]: No interbotix_xsarm_puppet package

### ISSUE THREAD

**Issue by deepaksinghcv** [Interbotix/interbotix_ros_manipulators#61]
### What happened?

I wanted to use the record/playback feature of my viper-x 300s. 
I tried to follow the instructions given at https://www.trossenrobotics.com/docs/interbotix_xsarms/ros_packages/record_and_playback.html but I notice that there is no package for interbotix_xsarm_puppet

I notice that the package is present in /examples directory.

Any help on launching the puppet record and playback from examples would be really useful.
Thank you

### Robot Model

vx300s

### Operating System

Ubuntu 20.04

### ROS Distro

ROS 2 Galactic

**Comment by LSinterbotix** [comment]
The interbotix_xsarm_puppet package has not been ported to ROS 2 yet and we don't have any plans in the near future to do so.
