### ISSUE TITLE
moveit error

### ISSUE THREAD

**Issue by Illidan41k** [Interbotix/interbotix_ros_manipulators#64]
I use galactic branch. There is an error in move_group initialization when the flag "use_gripper" is turned off. As I understood this flag doesn't affect on srdf, does it? 

[move_group-1] Error:   Joint 'wrist_rotate' declared as part of group 'interbotix_arm' is not known to the URDF
[move_group-1]          at line 168 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'ee_arm' declared as part of group 'interbotix_arm' is not known to the URDF
[move_group-1]          at line 168 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'gripper_bar' declared as part of group 'interbotix_arm' is not known to the URDF
[move_group-1]          at line 168 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'ee_bar' declared as part of group 'interbotix_arm' is not known to the URDF
[move_group-1]          at line 168 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'ee_gripper' declared as part of group 'interbotix_arm' is not known to the URDF
[move_group-1]          at line 168 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Link 'vx300s/left_finger_link' declared as part of group 'interbotix_gripper' is not known to the URDF
[move_group-1]          at line 149 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Link 'vx300s/right_finger_link' declared as part of group 'interbotix_gripper' is not known to the URDF
[move_group-1]          at line 149 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Warning: Group 'interbotix_gripper' is empty.
[move_group-1]          at line 245 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'wrist_rotate' declared as part of group state 'Home' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'wrist_rotate' declared as part of group state 'Upright' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'wrist_rotate' declared as part of group state 'Sleep' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'left_finger' declared as part of group state 'Grasping' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'right_finger' declared as part of group state 'Grasping' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'left_finger' declared as part of group state 'Released' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'right_finger' declared as part of group state 'Released' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'left_finger' declared as part of group state 'Home' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Joint 'right_finger' declared as part of group state 'Home' is not known to the URDF
[move_group-1]          at line 346 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp
[move_group-1] Error:   Link 'vx300s/ee_gripper_link' specified as parent for end effector 'interbotix_gripper' is not known to the URDF
[move_group-1]          at line 423 in /tmp/binarydeb/ros-galactic-srdfdom-2.0.3/src/model.cpp

**Comment by LSinterbotix** [comment]
The MoveIt and ROS Controllers configuration packages are not configured to take the use_gripper argument at this time.
