### ISSUE TITLE
[ERROR]: Can't find Dynamixel ID '1'

### ISSUE THREAD

**Issue by rpl-as-ucl** [Interbotix/interbotix_ros_manipulators#7]
I have a Widowx 250 arm, and I am failing launching the roslaunch interbotix_xsarm_control xsarm_control.launch robot_model:=wx250, by getting this error:

[ INFO] [1620733217.261312784]: Successfully retrieved motor configs from /home/dkanou/interbotix_ws/src/interbotix_ros_manipulators/interbotix_ros_xsarms/interbotix_xsarm_control/config/wx250.yaml.
[ INFO] [1620733217.300195792]: ID : 7, Model Number : 1060
[ INFO] [1620733217.348220795]: ID : 2, Model Number : 1020
[ERROR] [1620733217.428449616]: Can't find Dynamixel ID '1'

Any help?

**Comment by swiz23** [comment]
Hi @rpl-as-ucl,

My guess is that the baud-rate of the 'waist' servo (which is ID'd 1) is at an incorrect baudrate. You can fix this using the Dynamixel Wizard 2.0 tool. Read the section [here](https://github.com/Interbotix/interbotix_ros_core/blob/main/interbotix_ros_xseries/interbotix_xs_sdk/TROUBLESHOOTING.md#dynamixel-wizard-20-tool) to see if the 'waist' servo was left at its default baudrate of 57600 bps. It it was, use the Wizard to change it to 1 Mbps.

**Comment by rpl-as-ucl** [comment]
The wizard cannot find the robot at all...

**Comment by swiz23** [comment]
Did you make sure to open the Options tab in the Wizard and select the correct port, all baud-rates and the whole range of IDs?

**Comment by swiz23** [comment]
Closed due to lack of activity. Feel free to reopen if you have more questions.
