### ISSUE TITLE
[Bug]: Trying to simulate an interbotix arm

### ISSUE THREAD

**Issue by iordanidhsiord** [Interbotix/interbotix_ros_manipulators#95]
### What happened?

So we wanted to simulate the robotic arm ViperX250. We git cloned in our work space the "Interbotix_ros_manipulators" package and then we tried to launch the "xsarm_ros_control.launch".  
This is the error we get : ERROR: cannot launch node of type [interbotix_xs_sdk/xs_sdk_sim]: interbotix_xs_sdk
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/orestistzaf/thalassa_ws/src
ROS path [2]=/home/orestistzaf/kalokairi_ws/src
ROS path [3]=/home/orestistzaf/simulation_ws/src
ROS path [4]=/opt/ros/melodic/share
[ERROR] [1689528328.704309699]: PluginlibFactory: The plugin for class 'interbotix_xs_rviz/Interbotix Control Panel' failed to load.  Error: According to the loaded plugin descriptions the class interbotix_xs_rviz/Interbotix Control Panel with base class type rviz::Panel does not exist. Declared types are  rviz_map_plugin/ClusterLabel rviz_plugin_tutorials/Teleop rviz_visual_tools/RvizVisualToolsGui 
We also tried to git clone the "interbotix_ros_core" in the same workspace but we keep getting the same error. 

### Robot Model

vx250 

### Operating System

Ubuntu 18.04

### ROS Distro

ROS 1 Melodic

**Comment by LSinterbotix** [comment]
Please follow the [installation instructions](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros_interface/ros1/software_setup.html).

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
